just_thumbnail_homepage:
    path:     /hello/{name}
    defaults: { _controller: JustThumbnailBundle:Default:index }



just_thumbnail_extension:
    pattern:  /thumbnails/{mode}/{maxx}x{maxy}/{img}.{extension}
    defaults: { _controller: JustThumbnailBundle:Thumbnail:thumbnail }
    requirements:
        #mode: ~
        #maxx: ~
        #maxy: ~
        img: ".+"
        extension: "[a-z]{0,4}"

just_thumbnail_x_extension:
    pattern:  /thumbnails/{mode}/{maxx}x/{img}.{extension}
    defaults: { _controller: JustThumbnailBundle:Thumbnail:thumbnail }
    requirements:
        #mode: ~
        #maxx: ~
        img: ".+"
        extension: "[a-z]{0,4}"

just_thumbnail_y_extension:
    pattern:  /thumbnails/{mode}/x{maxy}/{img}.{extension}
    defaults: { _controller: JustThumbnailBundle:Thumbnail:thumbnail }
    requirements:
        #mode: ~
        #maxy: ~
        img: ".+"
        extension: "[a-z]{0,4}"

#JS\ThumbnailBundle\Controller
just_thumbnail:
    pattern:  /thumbnails/{mode}/{maxx}x{maxy}/{img}
    defaults: { _controller: JustThumbnailBundle:Thumbnail:thumbnail }
    requirements:
        #mode: ~
        #maxx: ~
        #maxy: ~
        img: ".+"

just_thumbnail_x:
    pattern:  /thumbnails/{mode}/{maxx}x/{img}
    defaults: { _controller: JustThumbnailBundle:Thumbnail:thumbnail }
    requirements:
        #mode: ~
        #maxx: ~
        img: ".+"

just_thumbnail_y:
    pattern:  /thumbnails/{mode}/x{maxy}/{img}
    defaults: { _controller: JustThumbnailBundle:Thumbnail:thumbnail }
    requirements:
        #mode: ~
        #maxy: ~
        img: ".+"