#JS\ThumbnailBundle\Controller
just_thumbnail:
    path:  /thumbnails/{mode}/{maxx}x{maxy}/{img}
    defaults: { _controller: JustThumbnailBundle:Thumbnail:thumbnail }
    requirements:
        #mode: ~
        #maxx: ~
        #maxy: ~
        img: ".+"

just_thumbnail_x:
    path:  /thumbnails/{mode}/{maxx}x/{img}
    defaults: { _controller: JustThumbnailBundle:Thumbnail:thumbnail }
    requirements:
        #mode: ~
        #maxx: ~
        img: ".+"

just_thumbnail_y:
    path:  /thumbnails/{mode}/x{maxy}/{img}
    defaults: { _controller: JustThumbnailBundle:Thumbnail:thumbnail }
    requirements:
        #mode: ~
        #maxy: ~
        img: ".+"
