ju_st_thumbnail_homepage:
    path:     /hello/{name}
    defaults: { _controller: JuStThumbnailBundle:Default:index }



ju_st_thumbnail_extension:
    pattern:  /thumbnails/{mode}/{maxx}x{maxy}/{img}.{extension}
    defaults: { _controller: JuStThumbnailBundle:Thumbnail:thumbnail }
    requirements:
        #mode: ~
        #maxx: ~
        #maxy: ~
        img: ".+"
        extension: "[a-z]{0,4}"

ju_st_thumbnail_x_extension:
    pattern:  /thumbnails/{mode}/{maxx}x/{img}.{extension}
    defaults: { _controller: JuStThumbnailBundle:Thumbnail:thumbnail }
    requirements:
        #mode: ~
        #maxx: ~
        img: ".+"
        extension: "[a-z]{0,4}"

ju_st_thumbnail_y_extension:
    pattern:  /thumbnails/{mode}/x{maxy}/{img}.{extension}
    defaults: { _controller: JuStThumbnailBundle:Thumbnail:thumbnail }
    requirements:
        #mode: ~
        #maxy: ~
        img: ".+"
        extension: "[a-z]{0,4}"

#JS\ThumbnailBundle\Controller
ju_st_thumbnail:
    pattern:  /thumbnails/{mode}/{maxx}x{maxy}/{img}
    defaults: { _controller: JuStThumbnailBundle:Thumbnail:thumbnail }
    requirements:
        #mode: ~
        #maxx: ~
        #maxy: ~
        img: ".+"

ju_st_thumbnail_x:
    pattern:  /thumbnails/{mode}/{maxx}x/{img}
    defaults: { _controller: JuStThumbnailBundle:Thumbnail:thumbnail }
    requirements:
        #mode: ~
        #maxx: ~
        img: ".+"

ju_st_thumbnail_y:
    pattern:  /thumbnails/{mode}/x{maxy}/{img}
    defaults: { _controller: JuStThumbnailBundle:Thumbnail:thumbnail }
    requirements:
        #mode: ~
        #maxy: ~
        img: ".+"