services:
    #    just_thumbnail.example:
    #        class: Just\ThumbnailBundle\Example
    #        arguments: [@service_id, "plain_value", %parameter%]
    just_thumbnail.twig.extension:
        class: Just\ThumbnailBundle\Twig\JustThumbnailExtension
        arguments: ["@router"]
        tags:
            -  { name: twig.extension }
        public: true

    Just\ThumbnailBundle\Services\ThumbnailService:
        arguments: [ "%just_thumbnail.imagesrootdir%", "%just_thumbnail.placeholder%","%just_thumbnail.expiretime%", "%kernel.project_dir%", "@cache", "%just_thumbnail.svgexportcommand%" ]
        public: true
        tags:
            - { name: just_thumbnail }

    Just\ThumbnailBundle\Controller\ThumbnailController:
        arguments:
            $thumbnailService: "just_thumbnail"