services:
#    just_thumbnail.example:
#        class: Just\ThumbnailBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]
    just_thumbnail.twig.extension:
        class: Just\ThumbnailBundle\Twig\JustThumbnailExtension
        arguments: [@router]
        tags:
            -  { name: twig.extension }